# Generated by Django 3.0 on 2021-01-07 16:34

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itemm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoo', embed_video.fields.EmbedVideoField()),
                ('cap', models.CharField(max_length=100)),
            ],
        ),
    ]
