# Generated by Django 3.0 on 2021-02-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eightn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eig', models.CharField(max_length=100)),
                ('eign', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='envvv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evv', models.CharField(max_length=100)),
                ('evvnn', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='labbb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labx', models.CharField(max_length=100)),
                ('labxx', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='nine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nine', models.CharField(max_length=100)),
                ('ninen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sevennn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sev', models.CharField(max_length=100)),
                ('sevn', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sixth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('six', models.CharField(max_length=100)),
                ('sixn', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='spnn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spp', models.CharField(max_length=100)),
                ('sppp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tennn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('tenn', models.CharField(max_length=100)),
            ],
        ),
    ]
